"""This type stub file was generated by pyright."""

from django.contrib import admin

class TypedModelAdmin(admin.ModelAdmin):
    def get_fields(self, request, obj=...): ...
    def save_model(self, request, obj, form, change):  # -> None:
        ...
