
[tox]
envlist = {py310,py311,py312,py313}-{dj52}
          {py312,py313}-{dj60}
          mypy
          pyright

[testenv]
changedir = {toxinidir}
commands =
    coverage run {envbindir}/pytest --ds=test_settings typedmodels/tests.py {posargs}
    coverage report --omit=typedmodels/test*

setenv = 
    PYTHONBREAKPOINT=ipdb.set_trace
deps =
    pyyaml
    coveralls
    ipdb
    pytest
    pytest-django
    pytest-sugar
    django-stubs
    django-stubs-ext
    dj52: Django~=5.2.0
    dj60: Django~=6.0.0
    mypy: mypy
    pyright: pyright

[testenv:mypy]
commands =
    python -m mypy .
basepython = python3.12

[testenv:pyright]
commands =
    python -m pyright
basepython = python3.12