# Generated by Django 5.2.17 on 2026-10-01 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_basemodelwithindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kennel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("testapp.cat", "cat"), ("testapp.dog", "dog")],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="kennel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="testapp.kennel"
            ),
        ),
        migrations.CreateModel(
            name="Cat",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.pet",),
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.pet",),
        ),
    ]
